package vn.hoanguyen.learning.bottomsheet

/**
 * Created by Hoa Nguyen on Jun 15 2021.
 */
object Utils {
    private const val STRING_LENGTH = 10
    private const val LIST_LENGTH = 200
    private const val ALPHANUMERIC_REGEX = "[a-zA-Z0-9]+"
    private val charPool: List<Char> = ('a'..'z') + ('A'..'Z') + ('0'..'9')

    fun randomPerson(): List<Person> {
        return (1..LIST_LENGTH)
            .map { Person(name = randomString()) }
    }

    fun randomFilms(): List<Person> {
        return (1..LIST_LENGTH)
            .map { Person(name = poolTextFilms[it]) }
    }

    fun randomString(): String {
        return (1..STRING_LENGTH)
            .map { i -> kotlin.random.Random.nextInt(0, charPool.size) }
            .map(charPool::get)
            .joinToString("")
    }

    private val poolTextFilms = listOf(
        "King's Speech, The Ferris Bueller's Day Off",
        "Ray Friday Night Lights",
        "No Country for Old Men Point Break",
        "Rise of the Planet of the Apes The Seventh Seal",
        "Cold Mountain Bourne Supremacy, The",
        "Full Metal Jacket Chicago",
        "Big Fat Liar Scarface",
        "Withnail and I Super Troopers",
        "Misery Braveheart",
        "S.W.A.T. Epic",
        "The Seven Samurai American Graffiti",
        "One Magic Christmas Transformers: Dark of the Moon",
        "Evil Dead 2 Charlie's Angels: Full Throttle",
        "Outlaw Josey Wales, The Khuda Kay Liye",
        "Red Dawn Crank",
        "Cheaper by the Dozen (2003) 127 Hours",
        "Quantum of Solace Latter Days",
        "Deuce Bigalow: European Gigolo VeggieTales: Tomato Sawyer and Huckleberry Larry's Big River Rescue",
        "Frenzy Something's Gotta Give",
        "Rocky Horror Picture Show, The Last Man on Earth, The",
        "Iron Jawed Angels X-men: The Last Stand",
        "Nashville Hot Shots",
        "Semi-Pro Xanadu",
        "Love Bug, The Robin Hood: Men in Tights",
        "In the Heat of the Night Presumed Innocent",
        "PCU After Hours",
        "X Files: I Want to Believe, The Mr. & Mrs. Smith",
        "Election Taxi",
        "Casino Inside Monkey Zetterland",
        "H[edit] Santa Clause, The",
        "In Cold Blood Jude",
        "Two Jakes, The American Gangster",
        "Fearless The Hunchback of Notre Dame II (2002)",
        "Blades of Glory 9",
        "Kelly's Heroes Napoleon Dynamite",
        "The Secret of NIMH 2: Timmy to the Rescue Ultraviolet",
        "Lara Croft: Tomb Raider Click",
        "Hide and Seek Black Rain",
        "Transformers: The Movie (Animated) Once Upon a Time in America",
        "Deewar Don Jon",
        "My Life Without Me Phantom of the Opera, The (2004)",
        "Willy Wonka & the Chocolate Factory Joe Dirt",
        "Air Force One Doctor Zhivago",
        "King Kong (1933) River Runs Through It, A",
        "Star Trek: Insurrection Compulsion",
        "Happy Feet Marnie",
        "Before Sunrise City of God",
        "Beyond the Valley of the Dolls Easy Rider",
        "Songwriter Glory Road",
        "Underdog Inside Man",
        "Meet Dave Trial, The (1962)",
        "G.I. Joe: Retaliation Mr. Mom",
        "Road Warrior, The Friday (1995)",
        "Singles Before Sunrise",
        "Pride American Wedding",
        "Thunderbolt and Lightfoot Star Trek: Insurrection",
        "Untouchables, The Taxi",
        "Pride and Prejudice (2005) Swordfish",
        "Blade II Caine Mutiny, The",
        "Ben-Hur Bad and the Beautiful, The",
        "Mongol Hitch",
        "As Good As It Gets Born on the Fourth of July",
        "Rear Window Mummy Returns, The",
        "Little Giants Marnie",
        "Meet Me in St. Louis Better Than Chocolate",
        "Life of Brian Kung Fu Hustle",
        "My Own Private Idaho The Reader",
        "An Extremely Goofy Movie Alvin and the Chipmunks: The Squeakquel",
        "Mission to Mars Rosemary's Baby",
        "Lone Star Identity Thief",
        "His Girl Friday Fast and the Furious, The",
        "Garden State Harold & Kumar Go to White Castle",
        "Finding Neverland Hellboy",
        "Inglorious Basterds Day of the Jackal, The",
        "Day After Tomorrow, The Serpico",
        "Be Kind Rewind Miss Congeniality 2: Armed & Fabulous",
        "Last of the Mohicans, The Life Aquatic with Steve Zissou, The",
        "Monsters, Inc. Grindhouse",
        "I'm Not There Thunderbolt and Lightfoot",
        "Runaway Bride True Lies",
        "Raging Bull The Affair of the Necklace",
        "Lethal Weapon 3 Blair Witch Project, The",
        "Police Academy Dr. No",
        "Pacifier, The Arthur",
        "Walk to Remember, A Harry Potter and the Deathly Hallows – Part 2",
        "Charlie and the Chocolate Factory (2005) (for the 1971 film, see Willy Wonka & the Chocolate Factory) Boiler Room",
        "Ripley's Game Requiem for a Dream",
        "Drugstore Cowboy Beau Geste (1939)",
        "7 Pounds Cold Mountain",
        "Mulholland Falls Hustler, The",
        "PCU Omen, The",
        "Spy Hard Dracula (1992)",
        "Bicycle Thieves Wrestler, The",
        "Inception L. A. Story",
        "Joseph: King of Dreams Hellraiser: Hellworld",
        "Blade Unbreakable",
        "Dallas Buyers Club Next (2007)",
        "Bourne Ultimatum, The Captain America: The First Avenger",
        "Annie Boondock Saints, The",
        "Virgin Suicides, The The Hunger Games",
        "Saw VI Dragnet",
        "Kate & Leopold Bringing Up Baby",
        "Princess Mononoke Johnny Dangerously",
        "Rules of the Game, The Guarding Tess",
        "Shenandoah Robin Hood (2010)",
        "Beverly Hills Chihuahua Fantastic Four",
        "To Kill a Mockingbird Conan the Destroyer (1984)",
        "Saved! Kicking and Screaming",
        "Exorcist III, The Withnail and I",
        "Eragon Thing From Another World, The",
        "Cloudy with a Chance of Meatballs The Texas Chainsaw Massacre: The Beginning",
        "Soul Plane Inside Monkey Zetterland",
        "Clockwork Orange, A The Greatest Game Ever Played",
        "Manhattan Five Easy Pieces",
        "Dr. No Who Framed Roger Rabbit",
        "Moonlight Mile Scream 3",
        "Star Wars Episode II: Attack of the Clones Star Trek VI: The Undiscovered Country",
        "Wrestler, The Stage Fright",
        "What About Bob? Beverly Hills Chihuahua",
        "What Lies Beneath How the Grinch Stole Christmas (2000 live-action movie)",
        "Chinatown Captain America: The Winter Soldier",
        "Conan the Barbarian Three Musketeers, The (1973)",
        "Beast of Yucca Flats, The Wallace & Gromit in The Curse of the Were-Rabbit",
        "You Don't Mess with the Zohan Ghost Rider",
        "Grease Melody",
        "Iron Jawed Angels Casanova",
        "Quick and the Dead, The Mutiny on the Bounty (1962)",
        "Doctor Dolittle (1967) Mutiny on the Bounty (1962)",
        "Jurassic Park: The Lost World Without a Paddle",
        "Let's Be Cops Babe",
        "Vampires Suck Daredevil",
        "Criss Cross Cold Mountain",
        "Mr. Smith Goes to Washington Surrogates",
        "Breaking Away RoboCop",
        "Mr. Magorium's Wonder Emporium Speed",
        "Treasure Planet Chronicles of Riddick, The",
        "Bachelor Mother In Her Shoes",
        "Hannah and Her Sisters Crimson Tide",
        "Miracle on 34th Street Hollywood Shuffle",
        "Choke Terminator, The",
        "Wreck-It Ralph Total Recall",
        "Boys from Brazil, The Fight Club",
        "Barcelona Island of Dr. Moreau, The (1996)",
        "Pi Atlantic City",
        "Aliens in the Attic Trading Places",
        "Carnal Knowledge Meet the Fockers",
        "Driving Miss Daisy Dawn of the Dead (2004)",
        "Transformers: Age of Extinction The Stepfather",
        "Frozen (2013) Rapture, The",
        "All About My Mother In a Lonely Place",
        "Urban Cowboy Last Picture Show, The",
        "Rent I Am Sam",
        "Airplane II: The Sequel Mad Max 2: The Road Warrior",
        "Junebug Smokin' Aces",
        "Back to the Future Part II Driving Miss Daisy",
        "Resident Evil Wrath of the Titans",
        "Man for All Seasons, A Happy Gilmore",
        "Birds, The Star Trek: The Motion Picture",
        "Better Off Dead Kill Bill: Volume 1",
        "Crash (2004) Mission: Impossible",
        "Watchmen Barry Lyndon",
        "Mission: Impossible II History of Violence, A",
        "Hudsucker Proxy, The Clue",
        "Children's Hour, The Nebraska",
        "Stand by Me Toxic Avenger, The",
        "Junebug Wes Craven's New Nightmare",
        "Monty Python and the Holy Grail Once Were Warriors",
        "Coneheads Dan in Real Life",
        "Big Top Pee-wee 50 First Dates",
        "Joe Dirt American Tail: Fievel Goes West, An",
        "Terms of Endearment Don't Say a Word",
        "S.W.A.T. Mr. Holland's Opus",
        "Dan in Real Life Waiting...",
        "Ghosts Treasure of the Sierra Madre, The",
        "Fountainhead, The Meet the Spartans",
        "Cheaper by the Dozen (1950) Lost in Translation",
        "If.... Blue Jasmine",
        "Troll Back to the Future Part II",
        "Playing By Heart Legend of 1900, The",
        "Cold Mountain Super Size Me",
        "N[edit] Nightmare on Elm Street, A (2010)",
        "Beach, The Percy Jackson & the Olympians: The Lightning Thief",
        "Star Wars Episode I: The Phantom Menace Indiana Jones and the Kingdom of the Crystal Skull",
        "National Lampoon's Christmas Vacation Children of Men",
        "Kung Fu Panda Ikiru",
        "Resident Evil: Apocalypse The Wizard of Oz",
        "Snoopy, Come Home Brave",
        "Treasure of the Sierra Madre, The Dracula (1992)",
        "M[edit] Pineapple Express",
        "Reefer Madness‎ S.W.A.T.",
        "It Drop Dead Gorgeous",
        "Matewan Beverly Hills Cop III",
        "Fracture Cowboy Bebop: The Movie",
        "My Man Godfrey Zed & Two Noughts, A",
        "Dead Poets Society Lethal Weapon 4",
        "American Graffiti Twilight Zone: The Movie",
        "Casablanca Lion King 1½, The",
        "Primal Fear Deep Throat",
        "Gattaca West Side Story",
        "Scott Pilgrim vs. the World Man on Fire",
        "Osmosis Jones Harry Potter and the Deathly Hallows – Part 1",
        "Dracula (1992) Rope",
        "Rocky Horror Picture Show, The Underworld: Evolution",
        "Natural Born Killers Dance of the Dead",
        "Anna Karenina RockNRolla",
        "Team America: World Police Princess Diaries, The",
        "Hobbit: An Unexpected Journey, The Are We Done Yet?",
        "Tin Cup Clerks II",
        "Superman Returns Home Alone 2: Lost in New York",
        "Maverick Winter's Bone",
        "Abraham Lincoln: Vampire Hunter Big Fish",
        "After Hours Quills",
        "Wild Hogs Cube",
        "What Dreams May Come Field of Dreams",
        "Million Dollar Baby Mulholland Falls",
        "Outsiders, The Killers, The",
        "Madagascar 3: Europe's Most Wanted Dukes of Hazzard, The",
        "Rebound Grand Voyage, Le",
        "Fight Club S Club Seeing Double",
        "Never Give a Sucker an Even Break Gone in 60 seconds",
        "Ace Ventura: Pet Detective Crimson Tide",
        "Enemy at the Gates Wanted (2008)",
        "Wedding Date, The Boyhood",
        "Ace Ventura: Pet Detective Young Frankenstein",
        "Grifters, The Omkara",
        "Duel History of Violence, A",
        "Life or Something Like It Megamind",
        "Eight Legged Freaks Dylan Dog: Dead of Night",
        "Daddy Day Camp Dance of the Dead",
        "Green Zone Hellboy II: The Golden Army",
        "Ocean's Thirteen Ruling Class, The",
        "Dracula (1931) Away from Her",
        "Close Encounters Of The Third Kind Star Trek: The Motion Picture",
        "Ghost Dog: The Way of the Samurai What Lies Beneath",
        "Net, The Catch Me If You Can",
        "Black Hawk Down Wicker Man, The (2006)",
        "The Day the Earth Stood Still (2008) Precious: Based on the Novel \"Push\" by Sapphire",
        "Stand by Me Psycho (1960)",
        "Snowpiercer Madagascar (2005)",
        "Carlito's Way Ernest Goes to Jail",
        "8 Mile E[edit]",
        "World Is Not Enough, The Net, The",
        "Paper Chase, The High Noon",
        "Grey Zone, The All of Me",
        "Twilight Zone: The Movie Salvador",
        "The Great Outdoors Are We Done Yet?",
        "Scent of a Woman I Am Legend",
        "Hook United States of Leland, The",
        "Desperate Living Bound",
        "The Twilight Saga: Breaking Dawn - Part 2 Game 6",
        "The Mirror Has Two Faces Garfield",
        "Fame Harry Potter and the Prisoner of Azkaban",
        "D[edit] Lincoln (2012)",
        "Angel Heart Nine Lives of Fritz the Cat, The",
        "Liquid Sky Beavis and Butthead Do America",
        "Cruel Intentions Scary Movie 4",
        "Inglorious Basterds Hitler: The Rise of Evil",
        "Children's Hour, The Paper Chase, The",
        "Simon Birch Reality Bites",
        "City of Angels Star Wars Episode V: The Empire Strikes Back",
        "Sense and Sensibility Rope",
        "Schindler's List Pay It Forward",
        "Truman Show, The Poseidon",
        "Doors, The Pirates of the Caribbean: At World's End",
        "Versus You Got Served",
        "Schindler's List Carlito's Way",
        "Thor: The Dark World Friendly Persuasion",
        "On Golden Pond Bicycle Thieves",
        "Annie Hall She's the Man",
        "Die Hard With a Vengeance Get Shorty",
        "Tomcats Lovely Bones, The",
        "Final Fantasy: The Spirits Within Die Hard 2: Die Harder",
        "Italian Job, The (1969) She-Devil",
        "Latter Days Shrek the Third",
        "Der Fuehrer's Face Naked Gun, The",
        "Bicycle Thieves Office Space",
        "Princess Diaries 2, The: Royal Engagement Stranger than Fiction",
        "Beverly Hills Chihuahua Mad Max 2: The Road Warrior",
        "Little Giants Last of the Mohicans, The",
        "Harry Potter and the Sorcerer's Stone War of the Worlds (2005)",
        "Platoon Body Heat",
        "Man with Two Brains, The Night Shift",
        "Psycho (1960) Indiana Jones and the Temple of Doom",
        "Usual Suspects, The The Stepfather",
        "Salvador Wayne's World",
        "Edge, The Platoon",
        "Godfather, The: Part III Blood Diamond",
        "Usual Suspects, The Georgia Rule",
        "Drop Dead Fred Gentleman Prefer Blondes",
        "Withnail and I Fog of War, The",
        "Young Guns Ultimate Gift, The",
        "Big Trouble in Little China Monty Python and the Holy Grail",
        "War of the Worlds (2005) Point Break",
        "Failure to Launch Anastasia",
        "Naked Pirates of the Caribbean: At World's End",
        "Honeymoon in Vegas The SpongeBob SquarePants Movie",
        "Lord of the Rings: The Two Towers, The Shrek",
        "Madea: Family Reunion Mummy, The",
        "Teenage Mutant Ninja Turtles II: The Secret of the Ooze Fearless",
        "The Avengers (2012) Dance of the Dead",
        "Goonies, The Friends of Eddie Coyle, The",
        "Wes Craven's New Nightmare Big Fish",
        "Stand by Me Jackie Brown",
        "Paparazzi Back to the Future Part II",
        "Saboteur Raising Helen",
        "Babe Factory Girl",
        "Anastasia Lawrence of Arabia",
        "Wayne's World 2 Terminator 3: Rise of the Machines",
        "Déjà Vu Snow Dogs",
        "Mary and Max Original Sin",
        "Kids Are All Right, The SpongeBob Movie: Sponge Out of Water, The",
        "Punisher: War Zone Rage: Carrie 2, The",
        "The Hangover: Part II Mystery of Mamo",
        "Eurotrip Sophie's choice",
        "Volcano Dracula (1979)",
        "Sex Drive Mud",
        "How the Grinch Stole Christmas! (1966 cartoon TV movie) Nosferatu",
        "League of Extraordinary Gentlemen, The Desperate Living",
        "Tommy Boy Dr. Strangelove: Or How I Learned to Stop Worrying and Love the Bomb",
        "Urban Cowboy City on Fire",
        "Bolt Angels with Dirty Faces",
        "Book of Shadows: Blair Witch 2 The Lego Movie",
        "Yours, Mine and Ours (2005) The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        "Once Upon a Time in America Scream 3",
        "...And Justice For All Man of the Year",
        "Youth in Revolt Fountainhead, The",
        "Without a Paddle Thin Red Line, The (1998)",
        "Rules of the Game, The Ocean's Eleven (2001)",
        "Mr. Destiny Hurt Locker, The",
        "Producers, The (1968) Hannibal Rising",
        "Meet the Parents Sweetest Thing, The",
        "Jurassic Park: The Lost World Nanny McPhee",
        "Dirty Shame, A The Chronicles of Narnia: The Voyage of the Dawn Treader",
        "Giant Claw, The Young Guns II",
        "The Sixth Sense Albatross",
        "Soapdish Lost in Translation",
        "Breaking Up Halloween",
        "Sherlock Holmes White Men Can't Jump",
        "Good Will Hunting Disclosure",
        "Last Man on Earth, The Jurassic Park: The Lost World",
        "Hot Shots! Part Deux Thirteen Days",
        "Crocodile Dundee Cats & Dogs: The Revenge of Kitty Galore",
        "Long Kiss Goodnight, The Hard Eight",
        "Manhattan Project, The Liar, Liar",
        "Toy Story Nobody's Fool",
        "If Only Down to Earth",
        "Public Enemies G[edit]",
        "Crow, The The Ten Commandments",
        "Mr Death: The Rise & Fall of Fred A Leuchter Jr. Intolerable Cruelty",
        "She's the Man Pretty Woman",
        "Batman Forever Rush Hour 3",
        "Strange Days Being There",
        "Toy Story 2 Sleeping with the Enemy",
        "Deewar Peaceful Warrior",
        "Shining, The Notorious",
        "Eight Men Out Beautiful Mind, A",
        "Lion King 1½, The Pride and Prejudice (2005)",
        "Waking Life Bringing Up Baby",
        "Dances with Wolves Rage: Carrie 2, The",
        "Town, The (2010) Paul Blart: Mall Cop",
        "N[edit] Something Wicked This Way Comes",
        "Strange Brew Samurai X",
        "Nicholas & Alexandra Destry Rides Again",
        "Girl, Interrupted Texas Chain Saw Massacre, The",
        "National Lampoon's Animal House Pokemon",
        "Evil Dead, The Bug's Life, A",
        "Good Bye Lenin! West Side Story",
        "Bourne Ultimatum, The Nightmare on Elm Street 5: The Dream Child, A",
        "Vampire in Brooklyn Titanic (1953)",
        "JFK Mad Max 2: The Road Warrior",
        "League of Their Own, A Knocked Up",
        "Simon Birch Yes Man",
        "Lost Horizon Mean Streets",
        "Crying Game, The Reservoir Dogs",
        "Good Will Hunting On Golden Pond",
        "Reds Three Musketeers, The (1948)",
        "Verdict, The When Harry Met Sally...",
        "The Amityville Horror (2005) Killing Fields, The",
        "17 Again Battle: Los Angeles",
        "Reign Over Me Punisher, The",
        "G.I. Joe: Retaliation Star Trek: The Motion Picture",
        "X Files: I Want to Believe, The Moonrise Kingdom",
        "Cats & Dogs Christmas Carol, A (2009 film)",
        "Romy and Michele's High School Reunion The Sting",
        "Behind Enemy Lines Up in the Air",
        "Sky Captain and the World of Tomorrow Cloudy with a Chance of Meatballs",
        "WarGames Rocky Horror Picture Show, The",
        "Rebound Wet Hot American Summer",
        "Coming Home Braindead",
        "Pirate Radio (a.k.a. The Boat That Rocked) Madagascar 3: Europe's Most Wanted",
        "Zombieland H[edit]",
        "Evan Almighty Man with Two Brains, The",
        "The Chronicles of Narnia: The Voyage of the Dawn Treader 400 Blows, The",
        "Orgazmo 50/50",
        "Disturbing Behavior Step Brothers",
        "The Wizard of Oz Believer, The",
        "3:10 to Yuma Jeremiah Johnson",
        "Puss in Boots Death Rides a Horse",
        "Sense and Sensibility Don Juan DeMarco",
        "Deewar Xanadu",
        "Margot at the Wedding Khuda Kay Liye",
        "Officer and a Gentleman, An Austin Powers: The Spy Who Shagged Me",
        "Planes, Trains, and Automobiles Messenger, The",
        "28 Days Later Beetlejuice",
        "Planes Daydream Nation",
        "Inventing the Abbotts Dukes of Hazzard, The",
        "Longest Day, The Raising Arizona",
        "Batman Forever Star Wars Episode IV: A New Hope",
        "From Here to Eternity Naked City, The",
        "Pacific Rim Outside Providence",
        "Kung Fu Panda 2 Tinker Bell",
        "Out of the Past Thor",
        "Shoot 'Em Up Eight Crazy Nights",
        "Herbie Goes to Monte Carlo Star Wars: The Clone Wars",
        "Big Blade Runner",
        "Oz the Great and Powerful Italian Job, The (1969)",
        "Talladega Nights: The Ballad of Ricky Bobby Nanny McPhee",
        "Traffic Lucas",
        "Across the Universe Corpse Bride",
        "Ghostbusters II Beautiful Mind, A",
        "Lost in Space Velvet Goldmine",
        "Arthur 7 Pounds",
        "Guarding Tess Adam's Rib",
        "It's a Mad, Mad, Mad, Mad World Craft, The",
        "Grumpy Old Men Jumanji",
        "Last Unicorn, The Hostel",
        "How to Train Your Dragon 2 Videodrome",
        "Mission: Impossible Bucket List, The",
        "Mulan THX 1138",
        "Letters to Juliet Alive",
        "Woman of the Year This Is the End",
        "Better Off Dead Evil Dead (2013)",
        "Night at the Museum Star Trek VI: The Undiscovered Country",
        "Fountainhead, The When a Man Loves a Woman",
        "Mist, The Game, The",
        "Quantum of Solace Ever After",
        "Black Book Harold and Maude",
        "Star Wars Episode I: The Phantom Menace Doctor Zhivago",
        "Red Eye 50 First Dates",
        "Cloverfield Craft, The",
        "The Reader Conan the Destroyer (1984)",
        "Iron Jawed Angels Harold & Kumar Escape from Guantanamo Bay",
        "Ice Age: Dawn of the Dinosaurs Casualties of War",
        "Legend of the Guardians: The Owls of Ga'Hoole The Mirror Has Two Faces",
        "Sex Drive Vertical Limit",
        "Bad Boys II Cape Fear (1991 film)",
        "Goonies, The Deer Hunter, The",
        "Other Guys,The Click",
        "Cop and a Half Cursed",
        "Dawn of the Dead (2004) Cheaper by the Dozen 2",
        "Doctor Zhivago Homeward Bound: The Incredible Journey",
        "Woman of the Year Room, The",
        "Savages, The Live and Let Die",
        "Guess Who's Coming to Dinner Pinocchio 3000 (2004)",
        "Saw Dr. Dolittle 2",
        "Naked Manchurian Candidate, The (1962)",
        "Sleeping Beauty If Only",
        "Net, The Fortune Cookie, The",
        "Midnight Run Liar, Liar",
        "Wicker Man, The (1973) My Bloody Valentine 3D",
        "Whiplash (2014) Legally Blonde 2: Red, White and Blonde",
        "Major Payne Malcolm X",
        "Dial M for Murder Phantom of the Opera, The (2004)",
        "That Thing You Do! Jeepers Creepers",
        "X-men: The Last Stand Soylent Green",
        "Last Starfighter, The Hostel",
        "Despicable Me 2 Kung Fu Panda 2",
        "Pride Football Factory, The",
        "Not Another Teen Movie Psycho II",
        "Harry Potter and the Deathly Hallows – Part 2 Beauty and the Beast",
        "Legend of Zorro, The Black Cat, The",
        "City of Angels Heist",
        "9 Despicable Me 2",
        "Happy Feet Day After Tomorrow, The",
        "Truman Show, The I Love You, Man",
        "Star Trek Nemesis Apocalypse Now",
        "Cats & Dogs Grand Hotel",
        "Opposite of Sex, The Waitress",
        "Police Academy Dracula (1931)",
        "Cowboy Bebop: The Movie Final Fantasy VII: Advent Children",
        "Bottle Rocket Cold Mountain",
        "Polyester Michael Clayton",
        "Craft, The Bananas",
        "Pride and Prejudice (2005) Star Trek V: The Final Frontier",
        "Godfather, The: Part II Runaway Bride",
        "Mary and Max Shaggy Dog, The",
        "Very Bad Things There's Something About Mary",
        "Office Space Mad Max 2: The Road Warrior",
        "Blade Thunderbolt and Lightfoot",
        "Johnny Dangerously Underworld",
        "VeggieTales: Tomato Sawyer and Huckleberry Larry's Big River Rescue Letters to Juliet",
        "Wanted (2008) Don't Be A Menace To South Central While Drinking Your Juice In The Hood",
        "The Twilight Saga: Breaking Dawn – Part 1 28 Days Later",
        "Planet of the Apes (1968) Jennifer's Body",
        "Cowboy Bebop: The Movie Midnight Cowboy",
        "Dylan Dog: Dead of Night Lady and the Tramp",
        "Beavis and Butthead Do America Moonlight Mile",
        "Are We There Yet? Harry Potter and the Deathly Hallows – Part 1",
        "Iron Man 3 Good Year, A",
        "The Alamo (1960) Predator",
        "Father of the Bride (1991) Punisher, The",
        "Human Traffic Defending Your Life",
        "Ernest Scared Stupid Klute",
        "The Twilight Saga: Breaking Dawn – Part 1 Hellraiser: Bloodline",
        "Greenberg Life of Brian",
        "Prozac Nation Honeymoon in Vegas",
        "Babe North by Northwest",
        "His Girl Friday Young and Innocent",
        "Black Hole, The 25th Hour",
        "Inconvenient Truth, An Hellraiser: Hellseeker",
        "Pee-wee's Big Adventure Notting Hill",
        "Scent of a Woman All the President's Men",
        "Sleeping with the Enemy Return of the Pink Panther, The",
        "Jacket, The In the Name of the Father",
        "Mad Max III: Beyond Thunderdome Dead Poets Society",
        "Z[edit] Lean on Me",
        "Way Way Back, The Inventing the Abbotts",
        "The Seventh Seal Taxi",
        "Madagascar (2005) Paradine Case, The",
        "Death to Smoochy Letters from Iwo Jima",
        "Naked Gun, The Mulholland Dr.",
        "I Now Pronounce You Chuck and Larry Taxi Driver",
        "Shining, The Candy",
        "Once Upon a Time in the West Night of the Hunter, The",
        "Rock, The Shoot 'Em Up",
        "My Sassy Girl Sophie's choice",
        "Go (1999) Space Chimps",
        "Hot Rod Everything You Always Wanted to Know About Sex* (*But Were Afraid to Ask)",
        "In Cold Blood Tron: Legacy",
        "Desperate Living Money Pit, The",
        "Hobbit: An Unexpected Journey, The Shadow, The",
        "Care Bears Movie II: A New Generation Caine Mutiny, The",
        "Punisher: War Zone Everything Is Illuminated",
        "Adjustment Bureau, The Texas Chain Saw Massacre, The",
        "Vertical Limit Iron Man",
        "Green Zone Cocktail",
        "O[edit] Meet the Robinsons",
        "Grifters, The Giant Claw, The",
        "Event Horizon Closer",
        "Money Pit, The George of the Jungle",
        "Postman Always Rings Twice, The Cheaper by the Dozen (1950)",
        "Step Brothers Care Bears Movie, The",
        "Angels & Demons All Dogs Go to Heaven 2",
        "VeggieTales: Gideon Tuba Warrior Thirteen",
        "Bad and the Beautiful, The Hud",
        "Orgazmo Spider-Man 2",
        "Shaun of the Dead Alien",
        "Saw V Angels with Dirty Faces",
        "Wicker Man, The (1973) Jack and Jill",
        "How to Lose a Guy in 10 Days Clockwork Orange, A",
        "Mutiny on the Bounty (1935) Star Wars Episode II: Attack of the Clones",
        "Léon Braveheart",
        "About Time Blue Jasmine",
        "Absence of Malice The Chronicles of Narnia: The Voyage of the Dawn Treader",
        "Van Helsing Ramayana: The Legend of Prince Rama",
        "Men in Black Once Were Warriors",
        "Iron Man 2 All Dogs Go to Heaven",
        "Tenacious D in The Pick of Destiny Magnolia",
        "Empire Records Master and Commander: The Far Side of the World",
        "Willow Mist, The",
        "Taxi Magnificent Seven, The",
        "Hamlet 2 Knute Rockne, All American",
        "Whiplash (2014) Open Season",
        "Brothers Grimm, The Underworld",
        "Confetti Rat Race",
        "Poseidon Adventure, The Daredevil",
        "Guess Who Mama (2013)",
        "Disclosure Zodiac",
        "1408 Black Christmas",
        "It Happened One Night Midnight Run",
        "Predator 2 Y Tu Mamá También",
        "From Dusk till Dawn Wag the Dog",
        "Trixie Very Bad Things",
        "The Rescuers Clueless",
        "Psycho (1960) Disturbia",
        "West Side Story Santa Clause 2, The",
        "Before Sunrise Top Gun",
        "Paycheck Watchmen",
        "Highlander (series) Big Fish",
        "Return to the Blue Lagoon Good Morning, Vietnam",
        "Miracle on 34th Street (1994) Tao of Steve, The",
        "Suspicion I Am Sam",
        "The Fox and the Hound 2 Charlie's Angels: Full Throttle",
        "Iron Jawed Angels Despicable Me 2",
        "Running Man, The Death Rides a Horse",
        "Gotti Angels with Dirty Faces",
        "Scarface Serpico",
        "Blow Bringing Up Baby",
        "Last Starfighter, The Confessions of a Dangerous Mind",
        "Disclosure Topaz",
        "Star Trek II: The Wrath of Khan Josie and the Pussycats",
        "L. A. Story Inferno",
        "Five Minutes of Heaven Don Juan DeMarco",
        "Few Good Men, A Natural, The",
        "Kindergarten Cop Casino Royale",
        "Out of Sight Hot Shots! Part Deux",
        "Once Upon a Time in America Before Midnight",
        "Alpha and Omega Italian Job, The (2003)",
        "Ocean's Eleven (2001) Clerks",
        "Outside Providence Clockwise",
        "Reds Blues Brothers 2000",
        "Rudy Bedazzled (2000)",
        "Ace Ventura: When Nature Calls Psycho (1998)",
        "Road Warrior, The Your Friend the Rat (short)",
        "Rob Zombie's Halloween Proposition, The",
        "Roxanne Beyond the Valley of the Dolls",
        "Idiocracy The Equalizer",
        "Malcolm X Gotti",
        "Hellraiser: Hellseeker The Master (2012)",
        "Best Years of Our Lives, The Only You (1994)",
        "Alvin and the Chipmunks Enemy of the State",
        "Battle of San Pietro, The Peacemaker, The",
        "Marty Flyboys",
        "It Happened One Night Riding the Bus with My Sister",
        "Young Rajah, The Beverly Hills Cop III",
        "Scooby-Doo Hunt for Red October, The",
        "Thin Man, The Space Chimps",
        "Bridge to Terabithia Man of the Year",
        "Training Day Osmosis Jones",
        "To Have and Have Not Mr Death: The Rise & Fall of Fred A Leuchter Jr.",
        "Death Becomes Her Carrie (1976)",
        "Godfather, The D[edit]",
        "Little Rascals, The Benny & Joon",
        "Saw IV The Last House on the Left (2009)",
        "The Wizard of Oz As Good As It Gets",
        "Ernest Goes to Jail Underdog",
        "Few Good Men, A The Texas Chainsaw Massacre: The Beginning",
        "Signs Live Free or Die Hard",
        "Protocol Yellow Submarine",
        "Lesbian Vampire Killers Cool and the Crazy‎",
        "Rambo: First Blood Part II Risky Business",
        "Holiday Inn Apocalypse Now",
        "Lorax, The Midsummer Night's Dream, A (1999)",
        "Rocky Balboa My Life Without Me",
        "League of Extraordinary Gentlemen, The Death Wish (I-V)",
        "Megamind Few Good Men, A",
        "Three Musketeers, The (1948) Star Wars Episode IV: A New Hope",
        "Tarzan II Troll",
        "King's Speech, The Training Day",
        "Not Another Teen Movie Boys from Brazil, The",
        "Racing Stripes Toy Story",
        "Sinbad: Legend of the Seven Seas Sgt. Bilko",
        "Kicking & Screaming Man with Two Brains, The",
        "Blind Date Treasure Planet",
        "Secret Window Strange Brew",
        "Glory Road Philadelphia",
        "Iron Jawed Angels Gone Baby Gone",
        "Karate Kid, Part II, The Donnie Brasco",
        "Negotiator, The Edward Scissorhands",
        "Core, The Road to El Dorado, The",
        "In Cold Blood Magnificent Seven, The",
        "Aguirre, the Wrath of God American Sniper",
        "Dumbo Meet Joe Black",
        "Thelma & Louise Iron Man 2",
        "Spider-Man 3 Karate Kid, Part III, The",
        "Beverly Hills Chihuahua Playing By Heart",
        "Brothers Grimm, The Kind Hearts and Coronets",
        "Polyester Five Minutes of Heaven",
        "Rock, The Ace Ventura: Pet Detective",
        "Up in Smoke Basic Instinct",
        "Get Carter Cinderella (1950)",
        "Meet John Doe How Green Was My Valley",
        "Gremlins Yours, Mine and Ours (1968)",
        "Home Alone 3 Public Enemies",
        "Who Framed Roger Rabbit If....",
        "Furry Vengeance King Arthur",
        "Longest Day, The Spirit: Stallion of the Cimarron",
        "Goonies, The Memoirs of a Geisha",
        "Minority Report Holes",
        "Dirty Harry Last Samurai, The",
        "Battle Royale Peacemaker, The",
        "Notorious Bedknobs and Broomsticks",
        "Wanted (2008) Conan the Barbarian",
        "Hellraiser: Bloodline Fortune Cookie, The",
        "Glen or Glenda Planet of the Apes (2001)",
        "JFK Bicentennial Man",
        "Proposition, The Victor/Victoria",
        "Ultraviolet All of Me",
        "Harvey Three Musketeers, The (1948)",
        "An American Tail: The Treasure of Manhattan Island Faster, Pussycat! Kill! Kill!",
        "Click Manhunter",
        "Fortune Cookie, The Howling, The",
        "Under The Tuscan Sun Atonement",
        "Braindead Moonlight Mile",
        "Underworld: Rise of the Lycans Contact",
        "Adjustment Bureau, The Just Friends",
        "Homeward Bound II: Lost in San Francisco Serenity",
        "K-PAX Honeymoon in Vegas",
        "Here Comes Pupcake Predator",
        "Deer Hunter, The Quick and the Dead, The",
        "Constant Gardener, The Down to Earth",
        "Santa Clause 2, The Wes Craven's New Nightmare",
        "Not Another Teen Movie Chicken Run",
        "Believer, The Paparazzi",
        "Suspicion Babylon A.D",
        "Tommy Boy Swingers",
        "Get Carter Breaking Away",
        "My Blueberry Nights High Noon",
        "Roman Holiday Three Days of the Condor",
        "Cinderella (1950) A Troll in Central Park",
        "Human Traffic Bug",
        "Legally Blonde 2: Red, White and Blonde Final Destination",
        "Lone Ranger, The (2013) Midsummer Night's Dream, A (1999)",
        "Your Highness Mr Death: The Rise & Fall of Fred A Leuchter Jr.",
        "Superstar Legally Blonde",
        "Die Hard Ace Ventura: Pet Detective",
        "Parenthood King Kong (2005)",
        "Wallace & Gromit in The Curse of the Were-Rabbit 300",
        "Gung Ho Red Dawn",
        "Hotel Rwanda Watchmen",
        "G.I. Joe: Retaliation Usual Suspects, The",
        "The Hills Have Eyes (2006) Doom",
        "Dark Knight Rises, The Amistad",
        "Horror Express The Reader",
        "Conquest of Space Anastasia",
        "W[edit] Don't Tell Mom the Babysitter's Dead",
        "First Wives Club, The Great Escape, The",
        "Sophie's choice Antitrust",
        "Net, The Pleasantville",
        "Peggy Sue Got Married Last Starfighter, The",
        "Peter Pan (1953) Harvey",
        "Return to Never Land The Muppets",
        "Harry Potter and the Sorcerer's Stone Beginners",
        "Omen, The Natural Born Killers",
        "Chumscrubber, The Swingers",
        "Underworld: Rise of the Lycans Pirates of the Caribbean: The Curse of the Black Pearl",
        "Megamind Fletch Lives aka Fletch 2",
        "Troll Dr. No",
        "No Way Out Red Dragon",
        "Blue Lagoon, The Italian Job, The (2003)",
        "Under Siege Lucky Number Slevin",
        "Casino Penelope",
        "Ghosts Perks of Being a Wallflower, The",
        "Planes: Fire & Rescue Crow, The",
        "Cutting Edge, The Five Easy Pieces",
        "Thor Madagascar (2005)",
        "Charlotte's Web (1973) Trick 'r Treat",
        "This is Spinal Tap The Day the Earth Stood Still (2008)",
        "Ace Ventura: Pet Detective Honeymoon in Vegas",
        "Friday Night Lights Royal Tenenbaums, The",
        "Jarhead K-PAX",
        "Lone Ranger, The (2013) 10 Things I Hate About You",
        "Salvador Harry Potter and the Sorcerer's Stone",
        "Uncle Buck Buckaroo Banzai",
        "You've Got Mail Cure, The (1995)",
        "Gentleman Prefer Blondes Down Periscope",
        "Wyatt Earp Zeitgeist: The Movie",
        "Zenon: Girl of the 21st Century The Ten Commandments",
        "I Know What You Did Last Summer Three Musketeers, The (1973)",
        "Fritz the Cat Departed, The",
        "Time To Kill, A Predator",
        "Fog of War, The Thumbsucker",
        "Shark Tale Get Shorty",
        "Robin Hood (2010) Notebook, The",
        "Ocean's Eleven (2001) Compulsion",
        "American Sniper Attack of the 50 Foot Woman",
        "It Happened One Night Jerry Maguire",
        "Deadfall Yours, Mine and Ours (1968)",
        "First Wives Club, The Armageddon",
        "Bourne Supremacy, The From Dusk till Dawn",
        "So I Married an Axe Murderer Saved!",
        "What Lies Beneath Jerry Maguire",
        "Fahrenheit 9/11 Lolita",
        "Talladega Nights: The Ballad of Ricky Bobby King's Speech, The",
        "Invasion of the Body Snatchers (1956) Remember Me",
        "Road House Presumed Innocent",
        "12 Years a Slave Hitch",
        "Snatch The Twilight Saga: Eclipse",
        "Wolverine, The Terminator Salvation",
        "Pillow Talk Young Rajah, The",
        "Jay and Silent Bob Strike Back The Curious Case of Benjamin Button",
        "Spaceballs Wings of Desire",
        "Erin Brockovich National Lampoon's European Vacation",
        "I[edit] Trainspotting",
        "Invictus Transformers: Dark of the Moon",
        "Red Dragon Darjeeling Limited, The",
        "Coach Carter Barcelona",
        "Deer Hunter, The Attack of the 50 Foot Woman",
        "Inception The Rescuers",
        "James and the Giant Peach Hoosiers",
        "25th Hour Bill and Ted's Excellent Adventure",
        "Toy Story 3 Never Let Me Go",
        "Aliens Cop and a Half",
        "Cutting Edge, The Shaun of the Dead",
        "Teachers BASEketball",
        "Star Wars Episode II: Attack of the Clones Face in the Crowd, A",
        "Dr. Dolittle 2 Sinatra",
        "Nim's Island Killer Klowns from Outer Space",
        "Many Adventures of Winnie the Pooh, The Thunderbolt and Lightfoot",
        "Queen, The Coneheads",
        "Zack and Miri Make a Porno Omkara",
        "Thomas Crown Affair, The Hoodwinked",
        "Factory Girl City of Angels",
        "Star Wars Episode VI: Return of the Jedi Herbie Goes Bananas",
        "Cider House Rules, The League of Their Own, A",
        "Purple Rose of Cairo, The She's All That",
        "Cloverfield Miss Congeniality",
        "SpongeBob Movie: Sponge Out of Water, The Zulu",
        "Nutty Professor 2 E[edit]",
        "Junebug 9",
        "I Heart Huckabees Meet the Spartans",
        "Catwoman I Love You, Man",
        "No Country for Old Men WarGames",
        "Orgazmo Coach Carter",
        "Eddie and the Cruisers Reservoir Dogs",
        "Spider-Man X-Men: First Class",
        "Benny & Joon Descendants, The",
        "Labyrinth The Hunchback of Notre Dame (1996)",
        "Walk Hard: The Dewey Cox Story Rainmaker, The (1997)",
        "Here Comes Pupcake Meet the Parents",
        "Chocolat Saving Silverman",
        "Princess Diaries, The Tears of the Black Tiger",
        "Fame Alice in Wonderland (2010)",
        "Long Kiss Goodnight, The TMNT",
        "Sweeney Todd: The Demon Barber of Fleet Street Mr. Peabody & Sherman",
        "Camille (1936) Howard the Duck",
        "Braindead Walk Hard: The Dewey Cox Story",
        "First Knight Sgt. Bilko",
        "Legends of the Fall Pawnbroker, The",
        "Troll Parallax View, The",
        "Zelig Deadfall",
        "Kentucky Fried Movie, The Blade Runner",
        "Lenny Swordfish",
        "Untouchables, The Manhattan Project, The",
        "Disclosure Major Payne",
        "History of Violence, A Green Lantern",
        "Ruling Class, The Sahara",
        "Paycheck Quick and the Dead, The",
        "Matrix Reloaded, The 13th Warrior, The",
        "Ransom (1996) School of Rock",
        "Dial M for Murder Little Rascals, The",
        "Manhattan Madea: Family Reunion",
        "Into the Blue Ransom (1996)",
        "TMNT And the Band Played On",
        "A.I. Artificial Intelligence About Last Night...",
        "Green Lantern Hard Candy",
        "Kill Bill: Volume 1 High Fidelity",
        "Hard Eight Ghost in the Shell 2: Innocence",
        "Dr. No Cats Don't Dance",
        "Imitation Game, The Rebecca",
        "Platoon Accused, The (1988)",
        "Dracula: Dead and Loving It Scarface",
        "Wolf of Wall Street, The (2013 film) Aliens in the Attic",
        "Psycho (1960) Hey Good Lookin'",
        "Van Wilder James Bond series",
        "Land of the Dead Revolver",
        "Hoosiers Precious: Based on the Novel \"Push\" by Sapphire",
        "First Knight Butch Cassidy and the Sundance Kid",
        "Precious: Based on the Novel \"Push\" by Sapphire Bridge on the River Kwai, The",
        "Many Adventures of Winnie the Pooh, The 300",
        "Dylan Dog: Dead of Night Accused, The (1988)",
        "Man Who Fell To Earth Hard Eight",
        "Herbie Goes Bananas Riding the Bus with My Sister",
        "X-Men: Days of Future Past Suspicion",
        "Gotti All About Steve",
        "Breakfast at Tiffany's Body Heat",
        "Love Actually Max Payne",
        "Nobody's Fool Wicker Man, The (2006)",
        "Kalifornia Dead Poets Society",
        "Jeremiah Johnson Star Wars Episode III: Revenge of the Sith",
        "Knute Rockne, All American Red Dragon",
        "Sabrina (1954) Talented Mr. Ripley, The",
        "Daydream Nation Capricorn One",
        "Sky Captain and the World of Tomorrow Aladdin",
        "Hot Fuzz Hammett",
        "Zed & Two Noughts, A Friendly Persuasion",
        "Beast of Yucca Flats, The Town, The (2010)",
        "Dragnet The Wizard of Oz",
        "Muppet Treasure Island Can't Hardly Wait",
        "Me, Myself & Irene Mary Poppins",
        "Mud Marley & Me",
        "James Bond series Ghost World",
        "Four Weddings And A Funeral Conquest of Space",
        "Bronx Tale, A Miss Pettigrew Lives for a Day",
        "Constant Gardener, The Once Upon a Time in the West",
        "American Pie 2 Scarface",
        "Craft, The 2012",
        "Presumed Innocent My Favorite Year",
        "Divine Secrets of the Ya Ya Sisterhood Crank",
        "Serendipity Alive",
        "Day at the Races, A Sweeney Todd: The Demon Barber of Fleet Street",
        "Jaws 3-D Three Days of the Condor",
        "Pink Floyd The Wall Titan AE",
        "Major League Tremors",
        "Bourne Legacy, The Harold & Kumar Escape from Guantanamo Bay",
        "Bee Season Replacements, The",
        "Mallrats Public Enemies",
        "A[edit] Atlantis: The Lost Empire",
        "Glen or Glenda Harvey",
        "Sex Drive Battle: Los Angeles",
        "History of the World: Part I Goodbye Girl, The",
        "Das Leben der Anderen Vicky Cristina Barcelona",
        "Devil's Advocate, The Reign Over Me",
        "Blown Away Talented Mr. Ripley, The",
        "Batman Begins Jeepers Creepers",
        "Choke History of the World: Part I",
        "Sleeping Beauty Ever After",
        "Winnie the Pooh Dumb and Dumberer: When Harry Met Lloyd",
        "Last Unicorn, The Dead Poets Society",
        "Bullitt Der Fuehrer's Face",
        "Rage: Carrie 2, The Wicker Man, The (2006)",
        "Nightmare on Elm Street 2: Freddy's Revenge, A City Slickers",
        "Dial M for Murder Mulan",
        "Rob Zombie's Halloween Smokin' Aces",
        "In Cold Blood Inferno",
        "Bound Stay Alive",
        "I Still Know What You Did Last Summer Teenage Mutant Ninja Turtles III",
        "Bedazzled (1967) City of Angels",
        "Camelot Grand Canyon (1991 film)",
        "Lady Eve, The Live and Let Die",
        "Cat Returns, The Children's Hour, The",
        "Heat Legally Blonde 2: Red, White and Blonde",
        "Divine Secrets of the Ya Ya Sisterhood Stranger than Fiction",
        "Letter from an Unknown Woman Bicentennial Man",
        "What Dreams May Come Scott Pilgrim vs. the World",
        "Nim's Island Big Top Pee-wee",
        "Great Debaters, The Bound",
        "Ghostbusters Sex and the City: The Movie",
        "N[edit] Fantastic Four",
        "Breaking Away The Twilight Saga: New Moon",
        "American Beauty Flags of Our Fathers",
        "Schindler's List Training Day",
        "10th Kingdom, The Fight Club",
        "Lord of War The secret of their eyes",
        "Flash Gordon 2046",
        "Poseidon Adventure, The 400 Blows, The",
        "Poseidon Thomas and the Magic Railroad",
        "Trixie Lady and the Tramp",
        "Christmas Story, A Jungle 2 Jungle",
        "Resident Evil Lesbian Vampire Killers",
        "Transformers: The Movie (Animated) Road Warrior, The",
        "Poltergeist Money Talks",
        "Full Metal Jacket Kindergarten Cop",
        "Death Becomes Her Hellraiser: Hellseeker",
        "Breakfast at Tiffany's Across the Universe",
        "Nine to Five Planes",
        "Return of the Pink Panther, The Deep Throat",
        "Dune Candy",
        "Outbreak Lord of War",
        "Kung Fu Panda Mr. Holland's Opus",
        "Friendly Persuasion Coyote Ugly",
        "Lords of Dogtown Over the Hedge",
        "Man with Two Brains, The Hours, The",
        "Road to El Dorado, The Twilight",
        "Chasing Liberty Zed & Two Noughts, A",
        "Pacific Rim Marnie",
        "Buffalo 66 Beauty and the Beast",
        "Lock, Stock and Two Smoking Barrels Click",
        "Zack and Miri Make a Porno First Blood",
        "Butterfly Effect, The He's Just Not That Into You",
        "Rat Race Hercules (1997)",
        "Enter the Dragon Manchurian Candidate, The (1962)",
        "Cabinet of Dr. Caligari, The Chasing Amy",
        "Running Man, The Varsity Blues",
        "Shoot 'Em Up Forbidden Kingdom, The",
        "Into the Blue But I'm a Cheerleader",
        "Bug's Life, A Balto",
        "Air Bud Pacific Rim",
        "District 9 Longest Day, The",
        "Karate Kid, Part III, The Lost Boys, The",
        "Transformers: Dark of the Moon Being There",
        "Fletch Carrie (2013)",
        "A.I. Artificial Intelligence Way Way Back, The",
        "Crash (1996) National Treasure: Book of Secrets",
        "Capricorn One Brothers Grimm, The",
        "Nine to Five Dedication",
        "Jeremiah Johnson Rainmaker, The (1997)",
        "Notting Hill Lion King 1½, The",
        "Patch Adams Ripley's Game",
        "Rear Window Soylent Green",
        "Diamonds Are Forever Underworld",
        "Freddy vs. Jason Lost Horizon",
        "Karate Kid, Part II, The How to Lose a Guy in 10 Days",
        "Towering Inferno, The Sense and Sensibility",
        "Dodgeball: A True Underdog Story 28 Weeks Later",
        "Red Dawn Crimson Tide",
        "Client, The Zed & Two Noughts, A",
        "Manhattan Being John Malkovich",
        "Rage: Carrie 2, The North by Northwest",
        "Shallow Hal Argo",
        "It Videodrome",
        "Terminator 2: Judgment Day Nightmare on Elm Street 3: Dream Warriors, A",
        "Alice in Wonderland (2010) The Secret",
        "Big Easy, The Gaslight (1944)",
        "Hard Boiled Teenage Mutant Ninja Turtles",
        "All of Me Dracula: Dead and Loving It",
        "Underworld: Rise of the Lycans Pirate Radio (a.k.a. The Boat That Rocked)",
        "Q[edit] Happening, The",
        "Terminal, The American Wedding",
        "Lethal Weapon 3 What Happens in Vegas",
        "Madagascar: Escape 2 Africa National Lampoon's Senior Trip",
        "Annie Hall Hackers",
        "Saint Joan Grosse Pointe Blank",
        "Return of Jafar, The Chasing Liberty",
        "Spider-Man 3 Nausicaä of the Valley of the Wind",
        "Iron Man Halloween",
        "Glory Road Mulholland Falls",
        "The Chronicles of Narnia: The Voyage of the Dawn Treader Vertigo",
        "Meatballs Public Enemies",
        "Red Eye Magnificent Ambersons, The"
    )
}